### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by damien916** [recharts/recharts#1372]
Hello recharts team, since V1.0.0, I have an error caused by lodash-es:

```
Unexpected token export
/Users/xx/Documents/Devs/xx/node_modules/lodash-es/isNil.js:25
export default isNil;
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/xx/Documents/Devs/xx/node_modules/recharts/lib/util/ReactUtils.js:8:15)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

My project run with Next.js and an internal dependency library that embed another internal dependency library that need recharts

**Comment by nolanrigo** [comment]
It seems that `lodash-es` is used on `lib/` build.
'cjs' build should use `lodash` instead ?

**Comment by ablamunits** [comment]
This is happening for us as well.
We have meanwhile fixated recharts to `1.0.0-beta.10` in `package.json`.

**Comment by mansdahlstrom1** [comment]
Experiencing the same issue, we also rolled back to `1.0.0-beta.10` as a workaround.

**Comment by xile611** [comment]
Sorry for the bug, It has been fixed in `1.0.1`.

**Comment by damien916** [comment]
Thanks for this fast fix !

**Comment by mansdahlstrom1** [comment]
Thanks!
