### ISSUE TITLE
Jest encountered an unexpected token - decimal.js-light/decimal.mjs:1980

### ISSUE THREAD

**Issue by ivan-nikitovic** [recharts/recharts#1495]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
```
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it'snot plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    .../node_modules/decimal.js-light/decimal.mjs:1980
    export var Decimal = clone(defaults);
    ^^^^^^

    SyntaxError: Unexpected token export

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (node_modules/recharts-scale/lib/getNiceTickValues.js:15:16)
      at Object.<anonymous> (node_modules/recharts-scale/lib/index.js:7:26)
```
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
1. Make sure version `1.3.0` is installed
2. Make sure you use `jest` to run tests
3. run `npm test`

## What is the expected behavior?
Tests are passing

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

```
node v8.9.1
macOS 10.13.6
recharts 1.3.0
jest 23.6.0
npm 6.4.1
```

**Comment by zemuldo** [comment]
I am having the same issue.
App created using create reactapp
- node v10
- recharts v1.3.0

**Comment by zemuldo** [comment]
I upgraded react-scripts from v1.1.1 to v1.1.5 and it worked. The solution is described [here](https://github.com/facebook/create-react-app/pull/4085/files)
