### ISSUE TITLE
Error when using ResponsiveContainer

### ISSUE THREAD

**Issue by ledinhthuc** [recharts/recharts#2832]
I'm using:
```
node v16.2.0
"webpack": "4.20.2",
"react": "16.5.2",
"react-dom": "16.5.2",
"recharts": "^2.1.9",
```

And i got this error:
```
ResponsiveContainer.js:52 Uncaught TypeError: Object(...) is not a function
    at eval (ResponsiveContainer.js:52:73)
    at updateForwardRef (react-dom.development.js:13412:20)
    at beginWork (react-dom.development.js:14114:16)
    at performUnitOfWork (react-dom.development.js:16416:12)
    at workLoop (react-dom.development.js:16454:24)
    at HTMLUnknownElement.callCallback (react-dom.development.js:145:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:195:16)
    at invokeGuardedCallback (react-dom.development.js:248:31)
    at replayUnitOfWork (react-dom.development.js:15745:5)
    at renderRoot (react-dom.development.js:16548:11)
```

My code:
```
import { ResponsiveContainer, LineChart, BarChart, Bar, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend } from 'recharts';
  ...
<ResponsiveContainer width="99%" height="100%">
    <BarChart data={data}>
        <XAxis dataKey="name" />
        <Tooltip />
        <Bar dataKey="data" fill="#009ef9" />
   </BarChart>
</ResponsiveContainer>
```
i also tried to use LineChart and faced the same problem

**Comment by premjogi** [comment]
@ledinhthuc above error is showing because versions of React and recharts are incompatible you should try to update your React to 17 or 18.

Here is the same code of yours : [https://codesandbox.io/s/icy-snow-cozr90](https://codesandbox.io/s/icy-snow-cozr90).

Hope this works for you.

**Comment by ckifer** [comment]
Closing this as resolved
