### ISSUE TITLE
React does not recognize the `textBreakAll` prop on a DOM element

### ISSUE THREAD

**Issue by Nefcanto** [recharts/recharts#3177]
The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.

---

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

Hello

As soon as I started using Recharts (2.3.2 at the moment of writing this issue) I see this error:

```
react_devtools_backend.js:4012 Warning: React does not recognize the `textBreakAll` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `textbreakall` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at Label (https://admin.project.local/node_modules/.vite/deps/recharts.js?v=401e0d79:18058:23)
    at g
    at https://admin.project.local/node_modules/.vite/deps/recharts.js?v=401e0d79:5633:24
    at LabelList (https://admin.project.local/node_modules/.vite/deps/recharts.js?v=401e0d79:18336:20)
    at g
    at https://admin.project.local/node_modules/.vite/deps/recharts.js?v=401e0d79:5633:24
    at Line2 (https://admin.project.local/node_modules/.vite/deps/recharts.js?v=401e0d79:25051:5)
    at svg
    at Surface (https://admin.project.local/node_modules/.vite/deps/recharts.js?v=401e0d79:5565:24)
    at div
    at CategoricalChartWrapper (https://admin.project.local/node_modules/.vite/deps/recharts.js?v=401e0d79:27924:7)
    at div
    at ResizeDetector2 (https://admin.project.local/node_modules/.vite/deps/recharts.js?v=401e0d79:10597:24)
    at https://admin.project.local/node_modules/.vite/deps/recharts.js?v=401e0d79:10838:21
    at LineChart (https://admin.project.local/src/Components/Dashboard/LineChart.jsx?t=1673676230067:18:3)
    at Chart (https://admin.project.local/src/Aggregates/Chart.jsx?t=1673676230067:22:3)
    at div
    at Widget (https://admin.project.local/src/Components/Dashboard/Widget.jsx:19:3)
    at div
    at div
    at Section (https://admin.project.local/src/Components/Dashboard/Section.jsx:35:3)
    at div
    at Dashboard (https://admin.project.local/src/Components/Dashboard/Dashboard.jsx:20:3)
    at ProjectDashboard
    at Unify (https://admin.project.local/src/Components/Unify.jsx:19:3)
    at RenderedRoute (https://admin.project.local/node_modules/.vite/deps/react-router-dom.js?v=72ea4741:2684:5)
    at Routes (https://admin.project.local/node_modules/.vite/deps/react-router-dom.js?v=72ea4741:3009:5)
    at MainRouting (https://admin.project.local/src/Panel/MainRouting.jsx?t=1673676230067:26:3)
    at div
    at div
    at div
    at Panel (https://admin.project.local/src/Panel/Panel.jsx?t=1673676230067:36:45)
    at InnerThemeProvider (https://admin.project.local/node_modules/.vite/deps/chunk-JGLZV44L.js?v=4343c9cd:2107:17)
    at ThemeProvider (https://admin.project.local/node_modules/.vite/deps/chunk-JGLZV44L.js?v=4343c9cd:764:5)
    at ThemeProvider2 (https://admin.project.local/node_modules/.vite/deps/chunk-JGLZV44L.js?v=4343c9cd:2115:5)
    at LocalizationProvider (https://admin.project.local/node_modules/.vite/deps/chunk-OUWKNFTI.js?v=4343c9cd:13942:17)
    at Router (https://admin.project.local/node_modules/.vite/deps/react-router-dom.js?v=72ea4741:2956:15)
    at BrowserRouter (https://admin.project.local/node_modules/.vite/deps/react-router-dom.js?v=72ea4741:3367:5)
```

**Comment by ckifer** [comment]
Hi @Nefcanto,

Can you give a little more context to the failure? What does your code look like? Can you repro in codesandbox?

**Comment by Nefcanto** [comment]
@ckifer yep you're right. The problem was that I was using `<div>` for `label` for `Line`.

```
import { Line } from 'recharts'

<LineChart>
            <Line
                type="monotone"
                dataKey={value}
                stroke="#8884d8"
                label={<div>hi</div>}
            />


```

I wish you could tell us somehow that we can't use simple HTML elements in labels and ticks. That took me a long time to figure it out.

**Comment by ckifer** [comment]
Ah, thanks. I'll make an issue to add this to the docs.

**Comment by Nefcanto** [comment]
@ckifer  thank you so much

**Comment by valentinaMarr** [comment]
I'd like to point out that the same issue appears even within the component `<Line />` in `<LineChart />` for the prop `dataKey` even though it has not been used a custom component to render the stroke (details in the screenshots). 
The only custom components are the dots with a custom tooltip, which - upon reading this issue - have been handled accordingly and do not throw any additional warning. 

I'm using a considerable variety of charts in the project i'm working on and it seems that only the LineChart is throwing this particular `dataKey` warning. 
Unfortunately i've not come up with a solution yet since i'm not understanding yet where the problem is exactly, but in the meantime i thought this could be a useful info for the discussion

<img width="1470" alt="Screenshot 2024-06-13 at 11 33 33" src="https://github.com/recharts/recharts/assets/127304575/212c1914-e741-48e0-954f-2917ff2a5126">
<img width="1460" alt="Screenshot 2024-06-13 at 11 33 13" src="https://github.com/recharts/recharts/assets/127304575/314b499f-e2ff-4ffe-a17a-1760b85cda38">

**Comment by PavelVanecek** [comment]
Is there any problems that this is causing? Yes it's red in the console, what else? Recharts has a habit of spreading everything everywhere so some of the internal props make it to DOM. Although that should be harmless as far as I understand.

**Comment by valentinaMarr** [comment]
Technically, not that i'm aware of. But, in my case, it has been requested to keep the console as clean as possible. Thus, if this is a warning due to a misuse of the library component - like injecting JSX elements, as far as it concern my case, and HTML elements into the content prop as mentioned before - or not, it would be nice to know it.

**Comment by ckifer** [comment]
This is all internal and nothing of you can do to resolve afaik. Internally, probably filterProps isn't doing its job. 

I wonder why we don't these when developing though... maybe storybook swallows them.
