### ISSUE TITLE
Document is not defined

### ISSUE THREAD

**Issue by ottos13** [recharts/recharts#337]
I'm using static data for some bar charts and the page was rendering fine. Once I've saved and closed out, I come back in the next time (without any code changes) and the page only displays the following. I'm unsure what I've missed when it was displaying correctly until this point. It's happened now on 2 files that I've tried creating from scratch.

ReferenceError: document is not defined
   at Text.calculateWordWidths (C:\Users\admin\Documents\ThemeOMeter\node_modules\recharts\lib\component\Text.js:101:17)
   at Text.updateWordsByLines (C:\Users\admin\Documents\ThemeOMeter\node_modules\recharts\lib\component\Text.js:81:43)
   at Text.componentWillMount (C:\Users\admin\Documents\ThemeOMeter\node_modules\recharts\lib\component\Text.js:67:12)
   at C:/Users/admin/Documents/ThemeOMeter/dist/server.bundle.js:13416:24
   at measureLifeCyclePerf (C:/Users/admin/Documents/ThemeOMeter/dist/server.bundle.js:13143:13)
   at ReactCompositeComponentWrapper.performInitialMount (C:/Users/admin/Documents/ThemeOMeter/dist/server.bundle.js:13415:10)
   at ReactCompositeComponentWrapper.mountComponent (C:/Users/admin/Documents/ThemeOMeter/dist/server.bundle.js:13326:22)
   at Object.mountComponent (C:/Users/admin/Documents/ThemeOMeter/dist/server.bundle.js:4052:36)
   at ReactDOMComponent.mountChildren (C:/Users/admin/Documents/ThemeOMeter/dist/server.bundle.js:12467:45)
   at ReactDOMComponent._createContentMarkup (C:/Users/admin/Documents/ThemeOMeter/dist/server.bundle.js:8074:33)
   at ReactDOMComponent.mountComponent (C:/Users/admin/Documents/ThemeOMeter/dist/server.bundle.js:7941:30)
   at Object.mountComponent (C:/Users/admin/Documents/ThemeOMeter/dist/server.bundle.js:4052:36)
   at ReactDOMComponent.mountChildren (C:/Users/admin/Documents/ThemeOMeter/dist/server.bundle.js:12467:45)
   at ReactDOMComponent._createContentMarkup (C:/Users/admin/Documents/ThemeOMeter/dist/server.bundle.js:8074:33)
   at ReactDOMComponent.mountComponent (C:/Users/admin/Documents/ThemeOMeter/dist/server.bundle.js:7941:30)
   at Object.mountComponent (C:/Users/admin/Documents/ThemeOMeter/dist/server.bundle.js:4052:36)
   at ReactDOMComponent.mountChildren (C:/Users/admin/Documents/ThemeOMeter/dist/server.bundle.js:12467:45)
   at ReactDOMComponent._createContentMarkup (C:/Users/admin/Documents/ThemeOMeter/dist/server.bundle.js:8074:33)
   at ReactDOMComponent.mountComponent (C:/Users/admin/Documents/ThemeOMeter/dist/server.bundle.js:7941:30)
   at Object.mountComponent (C:/Users/admin/Documents/ThemeOMeter/dist/server.bundle.js:4052:36)
   at ReactCompositeComponentWrapper.performInitialMount (C:/Users/admin/Documents/ThemeOMeter/dist/server.bundle.js:13439:35)
   at ReactCompositeComponentWrapper.mountComponent (C:/Users/admin/Documents/ThemeOMeter/dist/server.bundle.js:13326:22)
   at Object.mountComponent (C:/Users/admin/Documents/ThemeOMeter/dist/server.bundle.js:4052:36)
   at ReactCompositeComponentWrapper.performInitialMount (C:/Users/admin/Documents/ThemeOMeter/dist/server.bundle.js:13439:35)
   at ReactCompositeComponentWrapper.mountComponent (C:/Users/admin/Documents/ThemeOMeter/dist/server.bundle.js:13326:22) 

Here's my page code using static data only at this stage.
`/**
 * React Starter Kit (https://www.reactstarterkit.com/)
 *
 * Copyright © 2014-2016 Kriasoft, LLC. All rights reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE.txt file in the root directory of this source tree.
 */

import React, { Component, PropTypes } from 'react';
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import s from './SummaryPage.css';
import {Card, CardActions, CardTitle,CardMedia} from 'material-ui/Card';
import Paper from 'material-ui/Paper';
import { StyleSheet } from 'react-look'
import {BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,Legend,ComposedChart,Area} from 'recharts'

const title = 'Summary Page';

const dataScoreAvgs = [
      {name: 'MJ', avgScoreGiven: 4.0, avgScoreReceived: 2.400 },
      {name: 'Ben', avgScoreGiven: 3.0, avgScoreReceived: 1.398 },
      {name: 'Sarah', avgScoreGiven: 2.0, avgScoreReceived: 9.800 },
      {name: 'Dave', avgScoreGiven: 2.78, avgScoreReceived: 3.908 },
      {name: 'TK', avgScoreGiven: 1.890, avgScoreReceived: 4.800 },
      {name: 'Otto', avgScoreGiven: 2.390, avgScoreReceived: 3.800 },
      {name: 'James', avgScoreGiven: 3.490, avgScoreReceived: 4.30 },
];

const dataThemeRating = [
      {name: 'theme1', Picker: 'Otto', Score: 8.0},
      {name: 'theme2', Picker: 'Ben', Score: 7.5},
      {name: 'theme3', Picker: 'MJ', Score: 7.4},
      {name: 'theme4', Picker: 'Ben', Score: 7.12},
      {name: 'theme5', Picker: 'Dave', Score: 7.0},
];

class SummaryPage extends Component {

  static contextTypes = {
    onSetTitle: PropTypes.func.isRequired,
  };

  static propTypes = {
      songs: React.PropTypes.array,
      onCommentChange: React.PropTypes.func,
  }

  static defaultProps = {
      songs: [],
  }

  constructor(props) {
    super(props);
    this.state = {value: 1};
  }

  handleChange = (event, index, value) => this.setState({value});

  render() {
    const { songs } = this.props
    return (
      <div className="root">
        <div className={styles.containerStyle}>
          {this.props.path === '/' ? null : <h1>{this.props.title}</h1>}
          <div dangerouslySetInnerHTML={{ __html: this.props.content || '' }} />
          <Paper zDepth={3}>
            <Card className={styles.cardStyle}>
              <CardMedia className={styles.img}>
                <img src="/james-jean-talib.jpg" />
              </CardMedia>
              <CardTitle title="Summary"/>
                <BarChart width={400} height={400} data={dataScoreAvgs}
                    margin={{top: 5, right: 30, left: 20, bottom: 5}}>
                 <XAxis dataKey="name"/>
                 <YAxis/>
                 <CartesianGrid strokeDasharray="3 3"/>
                 <Tooltip/>
                 <Legend/>
                 <Bar dataKey="avgScoreGiven" fill="#8884d8" />
                 <Bar dataKey="avgScoreReceived" fill="#82ca9d" />
                </BarChart>
                <ComposedChart width={400} height={250} data={dataThemeRating}>
                <XAxis dataKey="name" />
                <YAxis type="number" name="Score" />
                <Tooltip />
                <Legend />
                <CartesianGrid stroke="#f5f5f5" />
                <Area type="monotone" dataKey="Score" fill="#8884d8" stroke="#8884d8" />
                <Bar dataKey="name" barSize={20} fill="#413ea0" />
                <Line type="monotone" dataKey="Picker" stroke="#ff7300" />
              </ComposedChart>
              <CardActions>
              </CardActions>
            </Card>
          </Paper>
        </div>
      </div>
    );
  }
}

const styles = StyleSheet.create({

    root: {
    margin: '0 auto',
    },
  containerStyle: {
    margin: '0 auto',
    padding: '0 0 40',
    maxWidth: '500',
    textAlign: 'center',

  },

  cardStyle: {

    maxWidth: '500',
    textAlign: 'center',

  },

  img: {
    display: 'inline-flex',
    maxWidth:'100%',
    maxHeight:'100%',
    height:'auto',
    width:'auto', /* ie8 */
  },

})

export default withStyles(s)(SummaryPage)
`

**Comment by xile611** [comment]
@ottos13 How about your version of recharts ?

**Comment by ottos13** [comment]
"recharts": "^0.15.3"

**Comment by xile611** [comment]
@ottos13 version 0.17.1  has fixed this problem.

**Comment by ottos13** [comment]
Thank you that has fixed my issue
