### ISSUE TITLE
Option ifOverflow='extendDomain' not working anymore for ReferenceLine and ReferenceArea

### ISSUE THREAD

**Issue by lukask-proxora** [recharts/recharts#3438]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/reference-element-ifoverflow-not-working-1jz7me)

### Steps to reproduce
Add a `ReferenceLine` or `ReferenceArea` that falls outside of the legend domains and set the prop `ifOverflow` to `'extendDomain'`.

### What is expected?
The domains are extended to fit the reference object.

### What is actually happening?
The reference object is drawn, but the domains are not extended. This basically behaves as the option `'visible'`.

| Environment | Info |
|---|---|
| Recharts | v2.4.3 |
| React | 18.2.0 |
| System | Ubuntu 22.04.2 LTS |
| Browser | Chromium 108.0.5359.124 |

---
This only happens since version 2.4.0
By changing the version in the code sandbox you can easily verify that it works correctly for version 3.3.2

**Comment by ckifer** [comment]
Aren't these the same?

https://github.com/recharts/recharts/issues/3379

**Comment by lukask-proxora** [comment]
@ckifer #3379 also occurs in earlier versions, so they are different bugs.

I had a quick look into the code and found out that the problem here is that the `yAxisId`s of the `ReferenceLine` and `YAxis` do not match. The `YAxis` gets 0 as default axis id while for the `ReferenceLine` it's undefined. 

It looks like this was introduced in version 2.4.0 when the default props of the `ReferenceLine` were removed.

**Comment by ckifer** [comment]
I haven't checked yet but I certainly don't remember removing anything from ReferenceLine. Weird

**Comment by lukask-proxora** [comment]
I think that was the PR: https://github.com/recharts/recharts/pull/3283

**Comment by ckifer** [comment]
Got it thank you, I'll take a look when I have time

**Comment by lukask-proxora** [comment]
Btw, as a workaround you can set `yAxisId={0}` on the `ReferenceLine`

**Comment by ckifer** [comment]
Basically this is the culprit

https://github.com/recharts/recharts/blob/master/src/util/DetectReferenceElementsDomain.ts#L39-L53

A **fatal** flaw of Recharts is that it takes advantage of defaultProps in the fact that it reaches into element props from a reference to that element. Line 43 tries to get `yAxisId` - because it was removed from default props it is no longer always set to 0. Default parameters don't get set until that component is actually called/invoked/rendered.

https://github.com/recharts/recharts/blob/master/src/util/ReactUtils.ts#L100

`findByType` is used to dig out children of a specific element type and reference their prop values before they have even been invoked in any way. This works when using `defaultProps` because it is static on the class/a property on the function component, but default params will not behave the same way. The only props that can be seen before invocation are the ones that are defined by the user (which isn't going to cut it). 

All that said I'm going to revert the commit to fix this

**Comment by ckifer** [comment]
Merged in #3455 

This will be released next minor version

**Comment by ckifer** [comment]
Released in 2.5!

**Comment by idealistraj9** [comment]
import React from 'react';
import { Icon } from 'react-icons-kit';
import { eyeOff } from 'react-icons-kit/feather/eyeOff';
import { eye } from 'react-icons-kit/feather/eye';

const CustomIcon = ({ icon = eyeOff, size = 20, ...props }) => {
  return <Icon icon={icon} size={size} {...props} />;
};

export default CustomIcon;

"use client";
import { useState } from "react";
import axios from 'axios';
import CustomIcon from "./Icon";
import { eyeOff } from 'react-icons-kit/feather/eyeOff';
import { eye } from 'react-icons-kit/feather/eye';
import { useRouter } from 'next/navigation'
import { toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { signIn } from "next-auth/react";

const LoginForm = ({ switchToSignupTab }: { switchToSignupTab: any }) => {
  const [showPassword, setShowPassword] = useState(false);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [result, setresult] = useState("");
  const type = showPassword ? "text" : "password";
  const icon = showPassword ? eye : eyeOff;
  const router = useRouter()

  const handleSignupClick = () => {
    switchToSignupTab();
    console.log("signup clicked");
  };

  const togglePasswordVisibility = () => {
    setShowPassword(!showPassword);
  };

  const handleLogin = async (e: { preventDefault: () => void; }) => {
    e.preventDefault();
    const result = await signIn("credentials", { username: email, password: password, redirect: true, callbackUrl: '/' })
  };

  return (
    <section className="shadow-none border-none outline-none">
      {/* {result} */}
      <div className="flex flex-col items-center justify-center h-full ">
        <div className="w-full bg-secondary rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700 ">
          <div className="p-6 space-y-4 md:space-y-6 sm:p-8">
            <h1 className="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
              Melden Sie sich bei Ihrem Konto an
            </h1>
            <form className="space-y-4 md:space-y-6" onSubmit={handleLogin}>
              <div>
                <label
                  htmlFor="email"
                  className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                >
                  Deine E-Mail
                </label>
                <input
                  type="email"
                  name="email"
                  id="email"
                  className="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                  placeholder="name@firma.ch"
                  onChange={(e) => setEmail(e.target.value)}
                />
              </div>
              <div>
                <label
                  htmlFor="username"
                  className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                >
                  Nutzername
                </label>
                <input
                  type="username"
                  name="username"
                  id="username"
                  className="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                  placeholder="Nike"
                />
              </div>
              <div>
                <label
                  htmlFor="password"
                  className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                >
                  Passwort
                </label>
                <div className="flex bg-white rounded-lg border-2 border-gray-300">
                  <input
                    type={type}
                    name="password"
                    id="password"
                    placeholder="••••••••"
                    className="bg-gray-50 border border-gray-300 border-none text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                    required
                    onChange={(e) => setPassword(e.target.value)}
                  />

                  <button
                    type="button"
                    onClick={togglePasswordVisibility}
                    className="relative transform -translate-y-1/2 text-gray-400 focus:outline-none m-1"
                  >
                    <CustomIcon icon={icon} size={20} />
                  </button>
                </div>



              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-start">
                  <div className="flex items-center h-5">
                    <input
                      id="remember"
                      aria-describedby="remember"
                      type="checkbox"
                      className="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-primary-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-primary-600 dark:ring-offset-gray-800"
                    />
                  </div>
                  <div className="ml-3 text-sm">
                    <label
                      htmlFor="remember"
                      className="text-gray-500 dark:text-gray-300"
                    >
                      Erinnere dich an mich
                    </label>
                  </div>
                </div>
                <a
                  href="#"
                  className="text-sm font-medium text-primary-600 hover:underline dark:text-primary-500"
                >
                  Passwort vergessen?
                </a>
              </div>
              <button
                type="submit"
                className="w-full text-secondary bg-primary hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800"
              >
                anmelden
              </button>
              <p className="text-sm font-light text-gray-500 dark:text-gray-400">
                Sie haben noch kein Konto?{" "}
                <button
                  type="button"
                  onClick={handleSignupClick}
                  className="font-medium text-primary-600 hover:underline dark:text-primary-500"
                >
                  Registrieren
                </button>
              </p>
            </form>
          </div>
        </div>
      </div>
    </section>
  );
};

export default LoginForm;


Warning: Icon: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at Icon (webpack-internal:///(ssr)/./node_modules/react-icons-kit/Icon.js:84:23)
    at CustomIcon (webpack-internal:///(ssr)/./components/Icon.js:17:23)
    at button
    at div
    at div
    at form
    at div
    at div
    at div
    at section
    at LoginForm (webpack-internal:///(ssr)/./components/LoginForm.tsx:25:22)
    at div
    at div
    at div
    at Login (webpack-internal:///(ssr)/./app/(pages)/login/page.tsx:18:86)
    at StaticGenerationSearchParamsBailoutProvider (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/static-generation-searchparams-bailout-provider.js:15:11)
    at Lazy
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:239:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:71:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:79:11)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:62:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:313:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:128:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:151:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:226:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/render-from-template-context.js:15:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:322:11)
    at Lazy
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:239:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:71:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:79:11)
    at NotFoundErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:54:9)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:62:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:313:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:128:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:151:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:226:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/render-from-template-context.js:15:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:322:11)
    at Lazy
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:239:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:71:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:79:11)
    at NotFoundErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:54:9)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:62:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:313:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:128:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:151:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:226:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/render-from-template-context.js:15:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:322:11)
    at Lazy
    at div
    at div
    at SessionProvider (webpack-internal:///(ssr)/./node_modules/next-auth/react/index.js:429:26)
    at Providers (webpack-internal:///(ssr)/./components/Providers.tsx:14:22)
    at body
    at html
    at RootLayout (webpack-internal:///(ssr)/./app/layout.tsx:19:23)
    at Lazy
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:71:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:79:11)
    at ReactDevOverlay (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:66:9)
    at HotReload (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:296:11)
    at Router (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:155:11)
    at ErrorBoundaryHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:99:9)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:128:11)
    at AppRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:421:13)
    at Lazy
    at Lazy
    at F:\PROJECT-2023\B2BMATCH\b2bmatch-ui-final\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:381577
    at F:\PROJECT-2023\B2BMATCH\b2bmatch-ui-final\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:381577
    at ServerInsertedHTMLProvider (F:\PROJECT-2023\B2BMATCH\b2bmatch-ui-final\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:17605)
Warning: SvgIcon: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at SvgIcon (webpack-internal:///(ssr)/./node_modules/react-icons-kit/SvgIcon.js:152:22)
    at i
    at Icon (webpack-internal:///(ssr)/./node_modules/react-icons-kit/Icon.js:84:23)
    at CustomIcon (webpack-internal:///(ssr)/./components/Icon.js:17:23)
    at button
    at div
    at div
    at form
    at div
    at div
    at div
    at section
    at LoginForm (webpack-internal:///(ssr)/./components/LoginForm.tsx:25:22)
    at div
    at div
    at div
    at Login (webpack-internal:///(ssr)/./app/(pages)/login/page.tsx:18:86)
    at StaticGenerationSearchParamsBailoutProvider (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/static-generation-searchparams-bailout-provider.js:15:11)
    at Lazy
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:239:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:71:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:79:11)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:62:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:313:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:128:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:151:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:226:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/render-from-template-context.js:15:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:322:11)
    at Lazy
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:239:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:71:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:79:11)
    at NotFoundErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:54:9)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:62:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:313:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:128:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:151:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:226:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/render-from-template-context.js:15:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:322:11)
    at Lazy
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:239:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:71:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:79:11)
    at NotFoundErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:54:9)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:62:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:313:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:128:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:151:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:226:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/render-from-template-context.js:15:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:322:11)
    at Lazy
    at div
    at div
    at SessionProvider (webpack-internal:///(ssr)/./node_modules/next-auth/react/index.js:429:26)
    at Providers (webpack-internal:///(ssr)/./components/Providers.tsx:14:22)
    at body
    at html
    at RootLayout (webpack-internal:///(ssr)/./app/layout.tsx:19:23)
    at Lazy
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:71:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:79:11)
    at ReactDevOverlay (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:66:9)
    at HotReload (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:296:11)
    at Router (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:155:11)
    at ErrorBoundaryHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:99:9)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:128:11)
    at AppRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:421:13)
    at Lazy
    at Lazy
    at F:\PROJECT-2023\B2BMATCH\b2bmatch-ui-final\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:381577
    at F:\PROJECT-2023\B2BMATCH\b2bmatch-ui-final\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:381577
    at ServerInsertedHTMLProvider (F:\PROJECT-2023\B2BMATCH\b2bmatch-ui-final\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:17605)
    
    
    please me to solve this

**Comment by idealistraj9** [comment]
> Basically this is the culprit
> 
> https://github.com/recharts/recharts/blob/4ee4124f3d73f9487b4b74d6aedac0f87af8d3a2/src/util/DetectReferenceElementsDomain.ts#L39-L53
> 
> A **fatal** flaw of Recharts is that it takes advantage of defaultProps in the fact that it reaches into element props from a reference to that element. Line 43 tries to get `yAxisId` - because it was removed from default props it is no longer always set to 0. Default parameters don't get set until that component is actually called/invoked/rendered.
> 
> https://github.com/recharts/recharts/blob/4ee4124f3d73f9487b4b74d6aedac0f87af8d3a2/src/util/ReactUtils.ts#L100
> 
> `findByType` is used to dig out children of a specific element type and reference their prop values before they have even been invoked in any way. This works when using `defaultProps` because it is static on the class/a property on the function component, but default params will not behave the same way. The only props that can be seen before invocation are the ones that are defined by the user (which isn't going to cut it).
> 
> All that said I'm going to revert the commit to fix this

can you help me in this code

**Comment by ckifer** [comment]
@idealistraj9 please see https://github.com/recharts/recharts/issues/3615
