### ISSUE TITLE
Regression - Tooltip crash

### ISSUE THREAD

**Issue by 0Lucifer0** [recharts/recharts#3578]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tooltip-with-customized-content-forked-wt7dbx?file=/src/App.tsx)

### Steps to reproduce
- Update to 2.6.0
- Add a tooltip inside an empty TreeMap with ResponsiveContainer
`
import "./styles.css";
import React from "react";
import { Tooltip, ResponsiveContainer, Treemap } from "recharts";

const data = [];

export default function App() {
  return (
    <ResponsiveContainer width="100%" height={400}>
      <Treemap data={[]} dataKey="value" nameKey="name">
        <Tooltip />
      </Treemap>
    </ResponsiveContainer>
  );
}
`

### What is expected?
Not to crash

### What is actually happening?
It is most likely due to this change https://github.com/recharts/recharts/commit/0b231b703bc7636795e4667c4b0db86b76eb26a6

It does not crash without the ResponsiveContainer

TypeError: Cannot read properties of null (reading 'x')
    at Tooltip (http://localhost:6006/vendors-node_modules_mui_icons-material_ArrowDropDown_js-node_modules_mui_icons-material_Arro-341c65.iframe.bundle.js:40382:18)
    at renderWithHooks (http://localhost:6006/vendors-node_modules_apollo_client_testing_react_MockedProvider_js-node_modules_storybook_add-b19fe8.iframe.bundle.js:75503:18)
    at mountIndeterminateComponent (http://localhost:6006/vendors-node_modules_apollo_client_testing_react_MockedProvider_js-node_modules_storybook_add-b19fe8.iframe.bundle.js:79267:13)
    at beginWork (http://localhost:6006/vendors-node_modules_apollo_client_testing_react_MockedProvider_js-node_modules_storybook_add-b19fe8.iframe.bundle.js:80780:16)
    at beginWork$1 (http://localhost:6006/vendors-node_modules_apollo_client_testing_react_MockedProvider_js-node_modules_storybook_add-b19fe8.iframe.bundle.js:86619:14)
    at performUnitOfWork (http://localhost:6006/vendors-node_modules_apollo_client_testing_react_MockedProvider_js-node_modules_storybook_add-b19fe8.iframe.bundle.js:85753:12)
    at workLoopSync (http://localhost:6006/vendors-node_modules_apollo_client_testing_react_MockedProvider_js-node_modules_storybook_add-b19fe8.iframe.bundle.js:85659:5)
    at renderRootSync (http://localhost:6006/vendors-node_modules_apollo_client_testing_react_MockedProvider_js-node_modules_storybook_add-b19fe8.iframe.bundle.js:85627:7)
    at recoverFromConcurrentError (http://localhost:6006/vendors-node_modules_apollo_client_testing_react_MockedProvider_js-node_modules_storybook_add-b19fe8.iframe.bundle.js:85043:20)
    at performConcurrentWorkOnRoot (http://localhost:6006/vendors-node_modules_apollo_client_testing_react_MockedProvider_js-node_modules_storybook_add-b19fe8.iframe.bundle.js:84943:22)

| Environment | Info |
|---|---|
| Recharts | v2.6.0 |
| React | 18 |
| System | Windows 11 |
| Browser | Brave |

**Comment by ckifer** [comment]
Oof, thank you. Will fix ASAP

**Comment by ckifer** [comment]
Should be good in 2.6.1 - thank you!

https://codesandbox.io/s/tooltip-with-customized-content-forked-7zhoe1?file=/src/App.tsx
