### ISSUE TITLE
Warning on install: npm WARN install:canvas@1.6.2

### ISSUE THREAD

**Issue by goums** [recharts/recharts#373]
Hi, 

I'm getting the following error and warning on npm install:

```
$ npm install recharts --save

> canvas@1.6.2 install /Users/sylvain/uplab/dashboard-react/node_modules/canvas
> node-gyp rebuild

./util/has_lib.sh: line 31: pkg-config: command not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/******/node_modules/canvas
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:canvas@1.6.2 canvas@1.6.2 install: `node-gyp rebuild`
npm WARN install:canvas@1.6.2 Exit status 1
```

I'm using versions:
```$ npm --version
3.10.3
$ node --version
v6.4.0```

This canvas issue does not seem to impact my recharts module however as it works fine for now.

**Comment by goums** [comment]
Sorry, this seemed to be caused by another module.

**Comment by xile611** [comment]
OK
