### ISSUE TITLE
TypeError: text.getComputedTextLength is not a function

### ISSUE THREAD

**Issue by bmamouri** [recharts/recharts#377]
When using XAxis and YAxis component I get the following error:

```
TypeError: text.getComputedTextLength is not a function
    at node_modules/recharts/lib/component/Text.js:111:42
    at Array.map (native)
    at Text.calculateWordWidths (node_modules/recharts/lib/component/Text.js:109:42)
    at Text.updateWordsByLines (node_modules/recharts/lib/component/Text.js:83:43)
    at Text.componentWillMount (node_modules/recharts/lib/component/Text.js:69:12)
    at node_modules/react-dom/lib/ReactCompositeComponent.js:348:23
    at measureLifeCyclePerf (node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
    at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:347:9)
    at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createContentMarkup (node_modules/react-dom/lib/ReactDOMComponent.js:653:32)
    at ReactDOMComponent.mountComponent (node_modules/react-dom/lib/ReactDOMComponent.js:520:29)
    at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createContentMarkup (node_modules/react-dom/lib/ReactDOMComponent.js:653:32)
```

I am using the simple example from the [docs](http://recharts.org/examples#SimpleLineChart), the recharts version is 0.19.0 and I am rendering it on the server.

**Comment by xile611** [comment]
@bmamouri Are you using recharts in server-side-render ?

**Comment by bmamouri** [comment]
@xile611: Yes, I forgot to mention that! Maybe I should just render the components that are dependent on getComputedTextLength only on the client side. Although that will cause the mismatch of rendered HTML on the server and client.

**Comment by xile611** [comment]
@bmamouri How about the version of recharts ?

**Comment by bmamouri** [comment]
@xile611: Updated the issue. My version is 0.19.0

**Comment by xile611** [comment]
@bmamouri  It seems `isSSR` return `false` in SSR.

**Comment by mattpage** [comment]
This fails for me in my enzyme tests. The reason it fails is that the isSsr export is testing for existence of 'document' like so:
```
export const isSsr = () => (typeof document === 'undefined');
```

My tests use jsdom:
```
global.document = jsdom.jsdom(html, {
  globalize: true,
  console: true,
  useEach: false,
  skipWindowCheck: false,
});
```
and so, of course, getComputedTextLength is called and it blows up.

If I modify isSsr to this:
```
export const isSsr = () => {
  return !(window && window.requestAnimationFrame);
}
```
it works.
