### ISSUE TITLE
fix warning message for YAxis and XAxis components

### ISSUE THREAD

**Issue by aynuayex** [recharts/recharts#4922]
Do you want to request a feature or report a bug?
here is the warning message:
```
chunk-3IHV7RO6.js?v=1350845e:521 Warning: XAxis: Support for defaultProps will be removed from function components 
in a future major release. Use JavaScript default parameters instead.
    at XAxis2 (http://192.168.8.3:5173/node_modules/.vite/deps/recharts.js?v=1350845e:26684:22)
    at svg
    at Surface (http://192.168.8.3:5173/node_modules/.vite/deps/recharts.js?v=1350845e:5255:24)
    at div
    at ChartLayoutContextProvider2 (http://192.168.8.3:5173/node_modules/.vite/deps/recharts.js?v=1350845e:23247:28)
    at CategoricalChartWrapper (http://192.168.8.3:5173/node_modules/.vite/deps/recharts.js?v=1350845e:27956:7)
    at div
    at http://192.168.8.3:5173/node_modules/.vite/deps/recharts.js?v=1350845e:8473:21
    at div
    at http://192.168.8.3:5173/node_modules/.vite/deps/chunk-RU2IYIAQ.js?v=1350845e:1790:50
    at Box3 (http://192.168.8.3:5173/node_modules/.vite/deps/chunk-SZHTQ3XM.js?v=1350845e:826:19)
    at DashboardGraph (http://192.168.8.3:5173/src/components/Dashboard/DashboardGraph.tsx?t=1724668909312:34:27)
    at div
    at http://192.168.8.3:5173/node_modules/.vite/deps/chunk-RU2IYIAQ.js?v=1350845e:1790:50
    at Box3 (http://192.168.8.3:5173/node_modules/.vite/deps/chunk-SZHTQ3XM.js?v=1350845e:826:19)
    at div
    at http://192.168.8.3:5173/node_modules/.vite/deps/chunk-RU2IYIAQ.js?v=1350845e:1790:50
    at Box3 (http://192.168.8.3:5173/node_modules/.vite/deps/chunk-SZHTQ3XM.js?v=1350845e:826:19)
    at div
    at http://192.168.8.3:5173/node_modules/.vite/deps/chunk-RU2IYIAQ.js?v=1350845e:1790:50
    at Box3 (http://192.168.8.3:5173/node_modules/.vite/deps/chunk-SZHTQ3XM.js?v=1350845e:826:19)
    at div
    at http://192.168.8.3:5173/node_modules/.vite/deps/chunk-RU2IYIAQ.js?v=1350845e:1790:50
    at Box3 (http://192.168.8.3:5173/node_modules/.vite/deps/chunk-SZHTQ3XM.js?v=1350845e:826:19)
    at Dashboard (http://192.168.8.3:5173/src/pages/Dashboard.tsx?t=1724668909312:30:27)
    at RenderedRoute (http://192.168.8.3:5173/node_modules/.vite/deps/react-router-dom.js?v=1350845e:4034:5)
    at Outlet (http://192.168.8.3:5173/node_modules/.vite/deps/react-router-dom.js?v=1350845e:4409:26)
    at div
    at http://192.168.8.3:5173/node_modules/.vite/deps/chunk-RU2IYIAQ.js?v=1350845e:1790:50
    at Box3 (http://192.168.8.3:5173/node_modules/.vite/deps/chunk-SZHTQ3XM.js?v=1350845e:826:19)
    at div
    at http://192.168.8.3:5173/node_modules/.vite/deps/chunk-RU2IYIAQ.js?v=1350845e:1790:50
    at Box3 (http://192.168.8.3:5173/node_modules/.vite/deps/chunk-SZHTQ3XM.js?v=1350845e:826:19)
    at App (http://192.168.8.3:5173/src/App.tsx?t=1724674527055:32:20)
    at RenderedRoute (http://192.168.8.3:5173/node_modules/.vite/deps/react-router-dom.js?v=1350845e:4034:5)
    at Outlet (http://192.168.8.3:5173/node_modules/.vite/deps/react-router-dom.js?v=1350845e:4409:26)
    at RequireAuth (http://192.168.8.3:5173/src/context/RequireAuth.tsx:22:20)
    at RenderedRoute (http://192.168.8.3:5173/node_modules/.vite/deps/react-router-dom.js?v=1350845e:4034:5)
    at Outlet (http://192.168.8.3:5173/node_modules/.vite/deps/react-router-dom.js?v=1350845e:4409:26)
    at PersistLogin (http://192.168.8.3:5173/src/context/PersistLogin.tsx:25:37)
    at RenderedRoute (http://192.168.8.3:5173/node_modules/.vite/deps/react-router-dom.js?v=1350845e:4034:5)
    at Outlet (http://192.168.8.3:5173/node_modules/.vite/deps/react-router-dom.js?v=1350845e:4409:26)
    at div
    at http://192.168.8.3:5173/node_modules/.vite/deps/chunk-RU2IYIAQ.js?v=1350845e:1790:50
    at Box3 (http://192.168.8.3:5173/node_modules/.vite/deps/chunk-SZHTQ3XM.js?v=1350845e:826:19)
    at RootLayout (http://192.168.8.3:5173/src/Layouts/RootLayout.tsx:22:22)
    at RenderedRoute (http://192.168.8.3:5173/node_modules/.vite/deps/react-router-dom.js?v=1350845e:4034:5)
    at RenderErrorBoundary (http://192.168.8.3:5173/node_modules/.vite/deps/react-router-dom.js?v=1350845e:3994:5)
    at DataRoutes (http://192.168.8.3:5173/node_modules/.vite/deps/react-router-dom.js?v=1350845e:5153:5)
    at Router (http://192.168.8.3:5173/node_modules/.vite/deps/react-router-dom.js?v=1350845e:4416:15)
    at RouterProvider (http://192.168.8.3:5173/node_modules/.vite/deps/react-router-dom.js?v=1350845e:4968:5)
    at AuthProvider (http://192.168.8.3:5173/src/context/AuthProvider.tsx:20:32)
```

**Comment by ckifer** [comment]
Please upgrade to the latest alpha version

See https://github.com/recharts/recharts/issues/3615

Closing as a duplicate
